### ISSUE TITLE
System UI has stoped

### ISSUE THREAD

**Issue by YumeMichi** [SlimRoms/frameworks_opt_slim#2]
ng7.0 branch

```
10-15 01:38:34.131 10233 10233 D AndroidRuntime: Shutting down VM
10-15 01:38:34.132 10233 10233 E AndroidRuntime: FATAL EXCEPTION: main
10-15 01:38:34.132 10233 10233 E AndroidRuntime: Process: com.android.systemui, PID: 10233
10-15 01:38:34.132 10233 10233 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void org.slim.action.ISlimActionsService.registerSlimStatusBar(org.slim.framework.internal.statusbar.ISlimStatusBar)' on a null object reference
10-15 01:38:34.132 10233 10233 E AndroidRuntime:        at org.slim.action.SlimActionsManager.registerSlimStatusBar(SlimActionsManager.java:69)
10-15 01:38:34.132 10233 10233 E AndroidRuntime:        at com.android.systemui.statusbar.slim.SlimStatusBar.start(SlimStatusBar.java:220)
10-15 01:38:34.132 10233 10233 E AndroidRuntime:        at com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:106)
10-15 01:38:34.132 10233 10233 E AndroidRuntime:        at com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:58)
10-15 01:38:34.132 10233 10233 E AndroidRuntime:        at com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:230)
10-15 01:38:34.132 10233 10233 E AndroidRuntime:        at com.android.systemui.statusbar.ServiceMonitor.-wrap5(ServiceMonitor.java)
10-15 01:38:34.132 10233 10233 E AndroidRuntime:        at com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)
10-15 01:38:34.132 10233 10233 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
10-15 01:38:34.132 10233 10233 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
10-15 01:38:34.132 10233 10233 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6077)
10-15 01:38:34.132 10233 10233 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-15 01:38:34.132 10233 10233 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
10-15 01:38:34.132 10233 10233 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
10-15 01:38:34.134  1612  6541 W ActivityManager: Process com.android.systemui has crashed too many times: killing!
```

**Comment by PRJosh** [comment]
Not where we do this. Ng7.0 isn't release
